/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellActivityRouteImport } from './routes/_shell.activity'
import { Route as ShellAnnouncementsRouteImport } from './routes/_shell.announcements'
import { Route as ShellAttendanceRouteImport } from './routes/_shell.attendance'
import { Route as ShellBookingsRouteImport } from './routes/_shell.bookings'
import { Route as ShellCafeRouteImport } from './routes/_shell.cafe'
import { Route as ShellCoachesRouteImport } from './routes/_shell.coaches'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellEquipmentRouteImport } from './routes/_shell.equipment'
import { Route as ShellEventsRouteImport } from './routes/_shell.events'
import { Route as ShellFacilitiesRouteImport } from './routes/_shell.facilities'
import { Route as ShellLostFoundRouteImport } from './routes/_shell.lost-found'
import { Route as ShellMembersRouteImport } from './routes/_shell.members'
import { Route as ShellMembershipsRouteImport } from './routes/_shell.memberships'
import { Route as ShellMerchandiseRouteImport } from './routes/_shell.merchandise'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellPaymentsRouteImport } from './routes/_shell.payments'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellScheduleRouteImport } from './routes/_shell.schedule'
import { Route as ShellServicesRouteImport } from './routes/_shell.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellActivityRoute = ShellActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnnouncementsRoute = ShellAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAttendanceRoute = ShellAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBookingsRoute = ShellBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCafeRoute = ShellCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoachesRoute = ShellCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEquipmentRoute = ShellEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEventsRoute = ShellEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFacilitiesRoute = ShellFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLostFoundRoute = ShellLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembersRoute = ShellMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembershipsRoute = ShellMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMerchandiseRoute = ShellMerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaymentsRoute = ShellPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScheduleRoute = ShellScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServicesRoute = ShellServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ShellActivityRoute
  '/announcements': typeof ShellAnnouncementsRoute
  '/attendance': typeof ShellAttendanceRoute
  '/bookings': typeof ShellBookingsRoute
  '/cafe': typeof ShellCafeRoute
  '/coaches': typeof ShellCoachesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/equipment': typeof ShellEquipmentRoute
  '/events': typeof ShellEventsRoute
  '/facilities': typeof ShellFacilitiesRoute
  '/lost-found': typeof ShellLostFoundRoute
  '/members': typeof ShellMembersRoute
  '/memberships': typeof ShellMembershipsRoute
  '/merchandise': typeof ShellMerchandiseRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payments': typeof ShellPaymentsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/schedule': typeof ShellScheduleRoute
  '/services': typeof ShellServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ShellActivityRoute
  '/announcements': typeof ShellAnnouncementsRoute
  '/attendance': typeof ShellAttendanceRoute
  '/bookings': typeof ShellBookingsRoute
  '/cafe': typeof ShellCafeRoute
  '/coaches': typeof ShellCoachesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/equipment': typeof ShellEquipmentRoute
  '/events': typeof ShellEventsRoute
  '/facilities': typeof ShellFacilitiesRoute
  '/lost-found': typeof ShellLostFoundRoute
  '/members': typeof ShellMembersRoute
  '/memberships': typeof ShellMembershipsRoute
  '/merchandise': typeof ShellMerchandiseRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payments': typeof ShellPaymentsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/schedule': typeof ShellScheduleRoute
  '/services': typeof ShellServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/activity': typeof ShellActivityRoute
  '/_shell/announcements': typeof ShellAnnouncementsRoute
  '/_shell/attendance': typeof ShellAttendanceRoute
  '/_shell/bookings': typeof ShellBookingsRoute
  '/_shell/cafe': typeof ShellCafeRoute
  '/_shell/coaches': typeof ShellCoachesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/equipment': typeof ShellEquipmentRoute
  '/_shell/events': typeof ShellEventsRoute
  '/_shell/facilities': typeof ShellFacilitiesRoute
  '/_shell/lost-found': typeof ShellLostFoundRoute
  '/_shell/members': typeof ShellMembersRoute
  '/_shell/memberships': typeof ShellMembershipsRoute
  '/_shell/merchandise': typeof ShellMerchandiseRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/payments': typeof ShellPaymentsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/schedule': typeof ShellScheduleRoute
  '/_shell/services': typeof ShellServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/announcements'
    | '/attendance'
    | '/bookings'
    | '/cafe'
    | '/coaches'
    | '/dashboard'
    | '/equipment'
    | '/events'
    | '/facilities'
    | '/lost-found'
    | '/members'
    | '/memberships'
    | '/merchandise'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/schedule'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/announcements'
    | '/attendance'
    | '/bookings'
    | '/cafe'
    | '/coaches'
    | '/dashboard'
    | '/equipment'
    | '/events'
    | '/facilities'
    | '/lost-found'
    | '/members'
    | '/memberships'
    | '/merchandise'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/schedule'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/activity'
    | '/_shell/announcements'
    | '/_shell/attendance'
    | '/_shell/bookings'
    | '/_shell/cafe'
    | '/_shell/coaches'
    | '/_shell/dashboard'
    | '/_shell/equipment'
    | '/_shell/events'
    | '/_shell/facilities'
    | '/_shell/lost-found'
    | '/_shell/members'
    | '/_shell/memberships'
    | '/_shell/merchandise'
    | '/_shell/notifications'
    | '/_shell/payments'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/schedule'
    | '/_shell/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/activity': {
      id: '/_shell/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ShellActivityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/announcements': {
      id: '/_shell/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof ShellAnnouncementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/attendance': {
      id: '/_shell/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ShellAttendanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bookings': {
      id: '/_shell/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof ShellBookingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cafe': {
      id: '/_shell/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof ShellCafeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/coaches': {
      id: '/_shell/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof ShellCoachesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/equipment': {
      id: '/_shell/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof ShellEquipmentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/events': {
      id: '/_shell/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof ShellEventsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/facilities': {
      id: '/_shell/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof ShellFacilitiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lost-found': {
      id: '/_shell/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof ShellLostFoundRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/members': {
      id: '/_shell/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ShellMembersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/memberships': {
      id: '/_shell/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof ShellMembershipsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/merchandise': {
      id: '/_shell/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof ShellMerchandiseRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/payments': {
      id: '/_shell/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ShellPaymentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedule': {
      id: '/_shell/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ShellScheduleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/services': {
      id: '/_shell/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ShellServicesRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellActivityRoute: typeof ShellActivityRoute
  ShellAnnouncementsRoute: typeof ShellAnnouncementsRoute
  ShellAttendanceRoute: typeof ShellAttendanceRoute
  ShellBookingsRoute: typeof ShellBookingsRoute
  ShellCafeRoute: typeof ShellCafeRoute
  ShellCoachesRoute: typeof ShellCoachesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEquipmentRoute: typeof ShellEquipmentRoute
  ShellEventsRoute: typeof ShellEventsRoute
  ShellFacilitiesRoute: typeof ShellFacilitiesRoute
  ShellLostFoundRoute: typeof ShellLostFoundRoute
  ShellMembersRoute: typeof ShellMembersRoute
  ShellMembershipsRoute: typeof ShellMembershipsRoute
  ShellMerchandiseRoute: typeof ShellMerchandiseRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPaymentsRoute: typeof ShellPaymentsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellScheduleRoute: typeof ShellScheduleRoute
  ShellServicesRoute: typeof ShellServicesRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellActivityRoute: ShellActivityRoute,
  ShellAnnouncementsRoute: ShellAnnouncementsRoute,
  ShellAttendanceRoute: ShellAttendanceRoute,
  ShellBookingsRoute: ShellBookingsRoute,
  ShellCafeRoute: ShellCafeRoute,
  ShellCoachesRoute: ShellCoachesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEquipmentRoute: ShellEquipmentRoute,
  ShellEventsRoute: ShellEventsRoute,
  ShellFacilitiesRoute: ShellFacilitiesRoute,
  ShellLostFoundRoute: ShellLostFoundRoute,
  ShellMembersRoute: ShellMembersRoute,
  ShellMembershipsRoute: ShellMembershipsRoute,
  ShellMerchandiseRoute: ShellMerchandiseRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPaymentsRoute: ShellPaymentsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellScheduleRoute: ShellScheduleRoute,
  ShellServicesRoute: ShellServicesRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
